### ISSUE TITLE
Comparation over PGSR?

### ISSUE THREAD

**Issue by LaFeuilleMorte** [zju-bmi-lab/SpikingGS#1]
Hi, Is there any experiment on the performance between spiking GS and pgsr?

**Comment by q-zh** [comment]
> Hi, Is there any experiment on the performance between spiking GS and pgsr?

Yes, we have compared with PGSR on NeRF-synthetic dataset. The results can be found at https://github.com/zju-bmi-lab/SpikingGS/blob/main/assets/supp.pdf

**Comment by zju-bmi-lab** [comment]
Yes, we have enclosed
