### ISSUE TITLE
Have you tried to use global&local FIF neuron on 3DGS?

### ISSUE THREAD

**Issue by LiuShuai086** [zju-bmi-lab/SpikingGS#3]
Excellent Work! Have you tried to use global&local FIF neuron on 3DGS? Whether the results would be like fig1(a) 2 without LOG?

**Comment by LMozart** [comment]
Hi. Thank you for your interest. Yes. According to our previous experiments, the FIF neurons will also work on 3DGS to improve the performance by suppressing LOPs. Detailed results may be released in the future if it is a concerned problem.

**Comment by LiuShuai086** [comment]
Hi, I've tried FIF neuron in my experiments and the result is great at beginning, however, the results would damage after reset_opacity_spike() (PSNR drops below 10db). Most opacities exceed Vth_opa, and Gs are larger than Vth_pdf. Could you provide me some advice to solve this problem?

**Comment by LMozart** [comment]
Could you please provide more details to reproduce your errors? Which dataset did you encounter this issue with? Did you modify the code? Normally, PSNR will not drop significantly on datasets used in our paper with the original code.

**Comment by LiuShuai086** [comment]
I used StreetGaussian as a baseline for custom AV scene experiment, applying FIF neuron trick without modeify this part code. The error occured at first call to reset_opacity_spike().

**Comment by shippoT** [comment]
Hi, I am afraid we are not sure about this bug. This didn't happen in our experiments. Please note that the current implementation has not yet been thoroughly tested across all scenarios. We will consider a broader implementation on other GS pipelines / scenes in the future.
